[package]
name = "civicsbot"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
kuchiki = "0.8.1"
reqwest = "0.12.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.128" }
tokio = {version = "1.40.0", features = ["full"]}
